### ISSUE TITLE
Header files

### ISSUE THREAD

**Issue by olavolav** [ChristophKirst/SimKernel#4]
It would be great to have some preprocessing in SimKernel control files. For instance, one could have a file for the general options and then a number of more specific control files (that only include the necessary bits which are not in the general one) that reference the general control file.

(Request copied from the [SourceForge repository](http://sourceforge.net/tracker/?func=detail&aid=3307552&group_id=313397&atid=1318913))

**Comment by Hmamouche** [comment]
Hi
I get an error when installing the library on osx. Can't find the mpi.h file.
Here an illustration of the make result:
make
g++ -I./include -O3 -MD -c -o obj/sim.o src/sim.cpp
g++ -I./include -O3 -MD -c -o obj/sim_io.o src/sim_io.cpp
g++ -I./include -O3 -MD -c -o obj/sim_signals.o src/sim_signals.cpp
g++ -I./include -O3 -MD -c -o obj/sim_io_manager.o src/sim_io_manager.cpp
g++ -I./include -O3 -MD -c -o obj/expression.o src/expression.cpp
g++ -I./include -O3 -MD -c -o obj/expression_basic.o src/expression_basic.cpp
g++ -I./include -O3 -MD -c -o obj/expression_sim.o src/expression_sim.cpp
g++ -I./include -O3 -MD -c -o obj/expression_extra.o src/expression_extra.cpp
g++ -I./include -O3 -MD -c -o obj/expression_parser.o src/expression_parser.cpp
ar rcs lib/sim.a obj/sim.o obj/sim_io.o obj/sim_signals.o obj/sim_io_manager.o obj/expression.o obj/expression_basic.o obj/expression_sim.o obj/expression_extra.o obj/expression_parser.o
mpic++ -DSIM_MPI -I./include -O3 -MD -c -o mpi/sim.o src/sim.cpp	
make: mpic++: No such file or directory
make: *** [mpi/sim.o] Error 1
Thanks in advance

**Comment by ChristophKirst** [comment]
HI
you need to install the external package mpi or open mpi on your computer (how that is done
for your machine/OS is best found via google), 
Its a package for parallel programming, mpic++ is the compiler.

Hope that helps..

**Comment by Hmamouche** [comment]
Hi,
Yes, now it works, Thanks.
Best,

Youssef
