### ISSUE TITLE
Compiler error on OSX Mavericks

### ISSUE THREAD

**Issue by olavolav** [ChristophKirst/SimKernel#7]
As discussed [here](https://github.com/olavolav/te-causality/issues/7), there seems to be a problem when installing SimKernel on OSX Mavericks.

Since it seems to be a SimKernel problem, I have closed the issue there, and let's continue the discussion here.

Javier have you tried the latest (library-style) version of SimKernel from Christoph's repository? (my changes have recently been merged)

edit: See specifically the error message [here](http://pastebin.com/7rkDMhF9).

**Comment by ChristophKirst** [comment]
merge should have fixed this issue now...
