### ISSUE TITLE
Inline private function breaks exe make target build

### ISSUE THREAD

**Issue by francesconero** [ChristophKirst/SimKernel#9]
Here's the compiler output:
> g++ -I./include -O3 -MD obj/sim.o obj/sim_io.o obj/sim_signals.o obj/sim_io_manager.o obj/expression.o obj/expression_basic.o obj/expression_sim.o obj/expression_extra.o obj/expression_parser.o test/main.o -o test/test  -lgsl -lgslcblas -L. -lrt 
test/main.o: In function `bool Sim::get<double>(std::string const&, double&, SimSignal const&)':
main.cpp:(.text._ZN3Sim3getIdEEbRKSsRT_RK9SimSignal[_ZN3Sim3getIdEEbRKSsRT_RK9SimSignal]+0x3b): undefined reference to `Sim::get_expr_nothrow(std::string const&, ExpressionPtr&, SimSignal const&, bool&)'
collect2: error: ld returned 1 exit status
Makefile:58: recipe for target 'exe' failed
make: *** [exe] Error 1

Specifically, if in file src/sim.cpp the inline attribute of 
> bool Sim::get_expr_nothrow(const ExprNameT& n, ExprPtrT& e, const SimSignal& sig, bool& eo)

is removed, the build completes without errors.
Is it possible that it's similar to this http://stackoverflow.com/questions/4769479/c-inlining-class-methods-causes-undefined-reference ?

I'm on Arch linux using gcc 4.9.1

**Comment by orlandi** [comment]
True!
Wonder why we weren't running into this before...
We have to apply this fix.

**Comment by ChristophKirst** [comment]
merge should now fixed this issue
